name: Terraform Deploy

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  terraform-plan:
    runs-on: terraform-runner
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Detect Changed Terraform Directory
        id: detect-dir
        run: |
          CHANGED_DIRS=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^terraform/' | cut -d '/' -f2 | sort -u | uniq)
          if [ -z "$CHANGED_DIRS" ]; then
            echo "No Terraform directory changes detected. Skipping..."
            exit 1
          fi
          echo "Detected Terraform directory changes: $CHANGED_DIRS"
          echo "TERRAFORM_DIR=$CHANGED_DIRS" >> $GITHUB_ENV  # Store in environment variable

      - name: Configure AWS-management Credentials 
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::902712839429:role/aws-actions-github-poc
          aws-region: us-east-1

      - name: Verify Terraform Directory Exists
        run: ls -R terraform/${{ env.TERRAFORM_DIR }}

      - name: Terraform Init
        working-directory: terraform/${{ env.TERRAFORM_DIR }}
        run: terraform init

      - name: Terraform Plan
        working-directory: terraform/${{ env.TERRAFORM_DIR }}
        run: terraform plan
