name: Terraform Deploy

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  terraform-plan:
    runs-on: terraform-runner
    if: contains(github.event.head_commit.modified, 'terraform/')  # Run only if Terraform directory is changed
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Detect Changed Directory
        id: changed-dir
        run: |
          DIRS=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^terraform/' | cut -d '/' -f2 | sort -u)
          if [ -z "$DIRS" ]; then
            echo "No changes in Terraform directories. Skipping..."
            exit 1
          fi
          echo "Detected Terraform directories changed: $DIRS"
          echo "TERRAFORM_DIR=$(echo $DIRS | head -n 1)" >> $GITHUB_ENV  # Pick the first changed dir

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::902712839429:role/aws-actions-github-poc
          aws-region: eu-west-1

      - name: Verify Terraform Directory
        run: ls -R terraform/$TERRAFORM_DIR

      - name: Terraform Init
        run: terraform init
        working-directory: terraform/$TERRAFORM_DIR

      - name: Terraform Plan
        run: terraform plan
        working-directory: terraform/$TERRAFORM_DIR
