name: Terraform Deploy

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Terraform
        run: |
          sudo apt-get update && sudo apt-get install -y gnupg software-properties-common
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg > /dev/null
          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
          sudo apt-get update && sudo apt-get install -y terraform

      - name: Configure AWS Credentials for AWS-1
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::902712839429:role/aws-actions-github-poc
          aws-region: eu-west-1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan (IAM Identity Center)
        run: terraform plan -target=module.iam_identity_center -out=iam_plan.tfplan

      - name: Configure AWS Credentials for AWS-2
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::AWS-2-ACCOUNT-ID:role/GitHub-Terraform-AWS2
          aws-region: eu-west-1

      - name: Terraform Plan (AWS-2 Infrastructure)
        run: terraform plan -target=module.aws_infrastructure -out=infra_plan.tfplan

  terraform-apply:
    needs: terraform-plan
    runs-on: ubuntu-latest
    environment: Production # Requires manual approval
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Terraform
        run: |
          sudo apt-get update && sudo apt-get install -y gnupg software-properties-common
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg > /dev/null
          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
          sudo apt-get update && sudo apt-get install -y terraform

      - name: Configure AWS Credentials for AWS-1
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::896695270469:role/aws-actions-github-poc
          aws-region: eu-west-1

      - name: Terraform Apply (IAM Identity Center)
        run: terraform apply iam_plan.tfplan

      - name: Configure AWS Credentials for AWS-2
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::AWS-2-ACCOUNT-ID:role/GitHub-Terraform-AWS2
          aws-region: eu-west-1

      - name: Terraform Apply (AWS-2 Infrastructure)
        run: terraform apply infra_plan.tfplan
